
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Function from Cloud Formation by Felix Vazquez - Code in S3 ZipFile'

Resources:
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
            S3Bucket: "felix-lambda-code"
            S3Key: "hello_lambda.zip"
        Description: Test with Cloud Formation
        FunctionName: Felix-hello-world
        Handler: lambda_function.lambda_handler
        Role: arn:aws:iam::776831754616:role/testRol
        Runtime: python2.7